# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'DiGA Training Programme'
description:      'Making the archaeology of Pakistan visible'
url:              'https://pages.ceres.rub.de'
baseurl:          '/diga'
copyright:        'DiGA project, 2021'
logo:             '/assets/logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
incremental: true
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  diga: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'diga_item' # the layout for the pages to use
    metadata:
      source: 'diga.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/diga' # path to the directory of images within `_data`
  asc: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'asc_item' # the layout for the pages to use
    metadata:
      source: 'asc.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/asc' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      diga:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - provenance
          - object_work_type
          - theme_subject
          - subject_actor
          - subject_place
          - subject_object
          - description
      asc:
        content: false
        fields:
          - label
          - object_type
          - provenance
          - custody
          - material
          - object_description

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    sub:
      - label: 'DiGA'
        link: '/about/'
      - label: 'Credits'
        link: '/credits/'
  - label: 'Collections'
    sub:
      - label: 'DiGA'
        link: '/collection/diga/'
      - label: 'Abba Sahib Cheena'
        link: '/collection/asc/'
  - label: 'Search'
    link: '/search/'
  - label: 'Reuse'
    link: '/reuse/'
  - label: 'Team'
    link: '/team/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'Made with Wax'
      link: 'https://github.com/minicomp/wax'
    - label: 'Credits'
      link: '/credits'
    - label: 'Contact'
      link: 'https://diga.ceres.rub.de'
  logos:
    - img: '/img/logo.png'

# FIN
