services:
    rake:
        image: digartefacts/wax
        entrypoint: ["bundle", "exec", "rake"]
        volumes:
            - .:/wax
        user: 1000:1000
    jekyll:
        image: digartefacts/wax
        entrypoint: ["bundle", "exec", "jekyll"]
        command: ["serve", "--host", "0.0.0.0"]
        volumes:
            - .:/wax
        ports:
            - "4000:4000"
        user: 1000:1000
